### ISSUE TITLE
Create a authentication middleware to protect routes

### ISSUE THREAD

**Issue by ashfaqshuvo007** [ashfaqshuvo007/BlogApi#1]
Use JWT for authentication tokens

**Comment by Pantex9** [comment]
Hi, I am interested in resolving this issue.

**Comment by ashfaqshuvo007** [comment]
> Hi, I am interested in resolving this issue.

Hey! I apologise. I solved it by myself. I am actually exploring .NET by building. If you are interested you can go through the code and may be try to find what we can do more.
